language: r
sudo: false
cache: packages
latex: false

branches:
  only:
    - master
    - cran

# This is the minimal set of R packages needed to run "R CMD check" on
# the package.
install:
  - R -e 'install.packages(c("devtools","etrunct","truncnorm","Rcpp","invgamma","SQUAREM","testthat","rmarkdown","knitr","ggplot2","mixsqp"))'

env:
  global:
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    - _R_CHECK_FORCE_SUGGESTS_: false

after_success:
  - Rscript -e 'covr::coveralls()'
  - Rscript -e 'covr::codecov()'
